build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"

run_test:
    image: python:2-alpine
    commands:
        - pip install -r requirements.txt
        - python testing.py

publish:
    docker:
        repo´: resoares/cicd_demoapp
        tag: latest
        username: resoares
        password: Cqs16419
        email: resoares@cisco.com

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
           username: admin
           password: 1vtG@lw@y
        urls:
            - https://mantlsandbox.cisco.com/marathon/v2/apps/class/resoares/restart?force=true

notify:
     spark:
          image: resoares/drone-spark
          auth_token: Boston Kubernetes Lab
          roomId: Y2lzY29zcGFyazovL3VzL1JPT00vYWJhOWFiYTAtZGNkZi0xMWU2LWE3ODItYTM1OTY2OWNkMzcx
