build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"

run_test:
    image: python:2-alpine
    commands:
        - pip install -r requirements.txt
        - python testing.py

publish:
    docker:
        repo´: resoares/cicd_demoapp
        tag: latest
        username: resoares
        password: Cqs16419
        email: resoares@cisco.com

